#!/bin/sh 
#
#	$Id: patches,v 1.1 2005/03/21 05:23:33 jerub Exp $	
#
#	For package users to generate patches for delivery back to the
#	maintenance team.
#
#	Requires a parameter that points to a directory that contains the
#	unpacked distribution source tree from Vanilla-*.tar.gz
#

if [ -z $1 ]; then
  echo "Usage: patches original-source-path"
  exit 1
fi

make clean
make rmdependencies
echo "Generating patches.diffs"
diff -u -r -N . $1 > patches.diffs

echo "Written patches.diffs"

