.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\"
.\" Copyright (C) 2006 Bob Tanner <tanner@real-time.com>
.\"
.\" This is free software; you can redistribute it and/or modify it under
.\" the terms of the GNU General Public License as published by the Free
.\" Software Foundation; either version 2, or (at your option) any later
.\" version.
.\" 
.\" This is distributed in the hope that it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\" 
.\" You should have received a copy of the GNU General Public License with
.\" your Debian GNU/Linux system, in /usr/share/common-licenses/GPL, or with
.\" the dpkg source package as the file COPYING.  If not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH NETREKD 1 "Dec 29th, 2006" "Debian GNU/Linux" "User Commands"
.SH NAME
netrekd \- the Netrek server
.SH DESCRIPTION
.B Netrek 
is the probably the first video game which can accurately be described 
as a "sport." It has more in common with basketball than with arcade games or 
Quake. Its vast and expanding array of tactics and strategies allows for many 
different play styles; the best players are the ones who think fastest, not 
necessarily the ones who twitch most effectively. It can be enjoyed as a twitch 
game, since the dogfighting system is extremely robust, but the things that really 
set Netrek apart from other video games are the team and strategic aspects. Team 
play is dynamic and varied, with roles constantly changing as the game state changes. 
Strategic play is explored in organized league games; after more than six years of 
league play, strategies are still being invented and refined.

Try the following options if you want more information.

netrekd [portfile] [debug] 
.PP 
netrekd stop
.PP
If you still didn't find the information you are looking for you might
consider posting a call for help to
.IR netrek-dev@us.netrek.org
