#!/bin/bash
#
# NAME
#   debian/postinst -- Debian postinst for netrek-server-vanilla
#
# DESCRIPTION
#   Place holder for post-installation maintainer scripts
#
# COPYRIGHT
#   Copyright (c) 2006 Bob Tanner <tanner@real-time.com>
#
# LICENSE
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License as published by the Free
#   Software Foundation; either version 2, or (at your option) any later
#   version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
#   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#   FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
#   more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc., 59
#   Temple Place, Suite 330, Boston, MA 02111-1307 USA.

# Source debconf library.
. /usr/share/debconf/confmodule

# Check user's answer
db_get netrek-server-vanilla/start_on_boot
if [ "$RET" = "true" ]; then
	/usr/sbin/update-rc.d netrek-server-vanilla defaults > /dev/null
fi

# Do not add the DEBHELPER stuff, we are doing the above ourselves.
exit 0
