#!/bin/bash
#
# NAME
#   debian/postrm -- Debian postrm for netrek-server-vanilla
#
# DESCRIPTION
#   Do a db_purge as the last thing in removing the package.
#
# COPYRIGHT
#   Copyright (c) 2006 Bob Tanner <tanner@real-time.com>
#
# LICENSE
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License as published by the Free
#   Software Foundation; either version 2, or (at your option) any later
#   version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
#   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#   FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
#   more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc., 59
#   Temple Place, Suite 330, Boston, MA 02111-1307 USA.

#DEBHELPER#

exit 0