#!/bin/sh

echo not ready
exit 1

VS=2.11.2-0

# apt-get install pbuilder

mkdir -p pbuilder

cat > pbuilder/sarge.rc <<EOF
BASETGZ=`pwd`/pbuilder/sarge.tgz
EXTRAPACKAGES=fakeroot
#MIRRORSITE=http://ftp.real-time.com/linux/debian/
MIRRORSITE=http://http.us.debian.org/debian/
OTHERMIRROR="deb http://quozl.linux.org.au/netrek ./|deb-src http://quozl.linux.org.au/netrek ./"
DISTRIBUTION=sarge
APTCACHE=`pwd`/pbuilder/aptcache
BUILDPLACE=`pwd`/pbuilder/build
BUILDUSERNAME=quozl
EOF

# as root
pbuilder create --configfile pbuilder/sarge.rc

# grab source manually
pbuilder login --configfile pbuilder/sarge.rc
echo "deb-src http://quozl.linux.org.au/netrek ./" >> /etc/apt/sources.list
apt-get --yes build-dep netrek-server-vanilla
apt-get --yes source netrek-server-vanilla

# future
wget --no-clobber http://quozl.linux.org.au/netrek/netrek-server-vanilla_${VS}.{dsc,tar.gz}
pbuilder build --configfile pbuilder/sarge.rc netrek-server-vanilla_${VS}.dsc
