#!/bin/sh
set -e

# verify we have the netrek server in our shell path
# you should source setpath before calling this, for example
# host:~$ . /usr/local/games/netrek-server-vanilla/lib/tools/setpath
getpath > /dev/null

# reset galaxy
setgalaxy r

# make all planets visible to all teams
for x in `seq 10 39`; do setplanet $x reveal; done

# make most of the romulan planets owned by federation
for x in `seq 10 18`; do setplanet $x owner fed; done

# move hyd near ear and flatten to one army
setplanet hyd y 80000 x 17000 armies 1

# move ori near ear and change ownership to rom
setplanet Ori y 83000 x 20000 owner rom

# teleport test player to ear, give kills, give armies
xtkill 0 tf
xtkill 0 k 3
xtkill 0 a

# take the planet
setplanet hyd be-taken-by 0

# allow time for conquer parade to finish
sleep 60

# shut down the game
setgame terminate
