#!/bin/sh
LIBDIR=/usr/local/games/netrek-server-vanilla
cd ${LIBDIR}

# reset galaxy
lib/tools/setgalaxy r

# make all planets visible to all teams
for x in `seq 10 39`; do lib/tools/setplanet $x reveal; done

# make most of the romulan planets owned by federation
for x in `seq 10 18`; do lib/tools/setplanet $x owner fed; done

# move hyd near ear and flatten to one army
lib/tools/setplanet hyd y 80000 x 17000 armies 1

# move ori near ear and change ownership to rom
lib/tools/setplanet ori y 83000 x 20000 owner rom

# teleport test player to ear, give kills, give armies
lib/tools/xtkill 0 tf
lib/tools/xtkill 0 k
lib/tools/xtkill 0 k
lib/tools/xtkill 0 k
lib/tools/xtkill 0 a

# instructions for test player
# take planet hyd to trigger conquer
# neut not enough

# start a set of robots
lib/og/robot -h localhost -Tr 2>/dev/null >/dev/null &
sleep 0.2
lib/og/robot -h localhost -Tr 2>/dev/null >/dev/null &
sleep 0.2
lib/og/robot -h localhost -Tr 2>/dev/null >/dev/null &
sleep 0.2
lib/og/robot -h localhost -Tr 2>/dev/null >/dev/null &
sleep 0.2
lib/og/robot -h localhost -Tf 2>/dev/null >/dev/null &
sleep 0.2
lib/og/robot -h localhost -Tf 2>/dev/null >/dev/null &
sleep 0.2
lib/og/robot -h localhost -Tf 2>/dev/null >/dev/null &

# allow time for last planet to be taken
sleep 600

# destroy all robots
killall robot

# destroy all client connections
killall ntserv

# allow time to run down
sleep 1

# destroy daemon
killall daemonII
