#!/bin/sh

# test script to produce x/y coordinates from moving a ship from centre
# of galactic in each direction using each warp speed

for speed in `seq 1 2`; do
	for dir in `seq 0 64`; do
		echo -n "${speed} "
		tools/setship 0 \
			x 50000 y 50000 dir ${dir} speed ${speed} \
			sleep 32 speed 0 sleep 6 get
	done
done

exit

gnuplot
set key off
set output "2007-02-19-ship-directions.png"
set terminal png size 1024,1024
set size square
set grid
plot [10000:90000] [10000:90000] \
"< egrep ^6 2007-02-18-ship-directions.log" using 9:11, \
"< egrep ^6 2007-02-19-ship-directions.log" using 9:11, \
"< egrep ^5 2007-02-18-ship-directions.log" using 9:11, \
"< egrep ^5 2007-02-19-ship-directions.log" using 9:11, \
"< egrep ^4 2007-02-18-ship-directions.log" using 9:11, \
"< egrep ^4 2007-02-19-ship-directions.log" using 9:11, \
"< egrep ^3 2007-02-18-ship-directions.log" using 9:11, \
"< egrep ^3 2007-02-19-ship-directions.log" using 9:11
exit
