#!/bin/sh

# test script to produce x/y coordinates from moving a torp from centre
# of galactic in each direction

for dir in `seq 0 255`; do
    tools/setship 1 x 50000 y 50000 dir ${dir} fire-test-torpedo ${dir} \
	sleep 6 show-torpedo-position-and-destroy
done

exit

# gnuplot
set key off
set output "2007-02-19-torp-directions.png"
set terminal png size 1024,1024
set size square
set grid
plot [35000:65000] [35000:65000] "2007-02-19-torp-directions.log" using 4:6
