#!/bin/sh

# test script to produce x/y coordinates from moving a torp from centre
# of galactic in each direction

for dir in `seq 0 255`; do
#   [set up static test environment]
    tools/setship 1 position 50000 50000 dir ${dir} speed 0
#   pause test-mode set-test-counter n
    tools/setgame pause test-mode set-test-counter 300
#   [set up dynamic test environment]
    tools/setship 1 no-wobble torp-speed 2 fire-test-torpedo ${dir}
#   resume wait-for-pause
    tools/setgame resume wait-for-pause
#   [examine result] */
    tools/setship 1 show-test-torpedo-position destroy-test-torpedo
    tools/setgame resume
done

exit

gnuplot
set key off
set output "2007-02-19-torp-directions-2.png"
set terminal png size 1024,1024
set size square
set grid
plot [35000:65000] [35000:65000] "2007-02-19-torp-directions.log" using 4:6, \
"2007-02-19-torp-directions-2.log" using 4:6
exit
