#!/bin/sh
set -e

# activated by daemon when a bloggable event occurs, such as a
# surrender, genocide or conquer
# $1 is the class of the event
# $2 is the name of the file written by the daemon with the details

# determine where to put the file
BLOG=`tools/getpath --localstatedir`/blog/$1

# create the directory if it does not yet exist
mkdir -p ${BLOG}

# move the file to the directory
mv $2 ${BLOG}

# refresh the static blog content
/usr/lib/cgi-bin/blosxom -f='etc/blosxom.conf' -password='netrek'
