#!/bin/sh
set -e

# activated by daemon when a surrender, genocide or conquer happens
# $1 is the name of the file written by the daemon with the details

BLOG=`tools/getpath --localstatedir`/blog/conquer
mkdir -p ${BLOG}
mv $1 ${BLOG}
/usr/lib/cgi-bin/blosxom -f='etc/blosxom.conf' -password='netrek'
