#!/bin/sh

cat <<EOF >trekon
#!/bin/sh

if [ -z \$NTSERV_PATH ]; then
    export NTSERV_PATH=\$1
fi

exec xbiff -update 60 -file \$NTSERV_PATH/on -name trekon \
           -xrm "trekon*emptyPixmap: \$NTSERV_PATH/trekoff.bitmap"\
           -xrm "trekon*fullPixmap: \$NTSERV_PATH/trekon.bitmap"
EOF
#!/bin/sh

cat <<EOF >trekon
#!/bin/sh

if [ -z \$NTSERV_PATH ]; then
    export NTSERV_PATH=\$1
fi

exec xbiff -update 60 -file \$NTSERV_PATH/on -name trekon \
           -xrm "trekon*emptyPixmap: \$NTSERV_PATH/trekoff.bitmap"\
           -xrm "trekon*fullPixmap: \$NTSERV_PATH/trekon.bitmap"
EOF
