/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gum (void);
GtkWidget* create_motd (void);
GtkWidget* create_message (void);
GtkWidget* create_open (void);
GtkWidget* create_saveas (void);
GtkWidget* create_welcome (void);
