#!/bin/sh
echo "`date` $1 $0 $2" >> admin.log
mail -s 'ban: $3' `whoami` << EOF
God observer: $1
Offending slot host name: $2
EOF
echo "# banned by admin command, `date`" >> .banned
echo "*@$2" >> .banned
echo "# banned by admin command, `date`" >> .access
echo "$2 n" >> .access

